# Generated by Django 5.1.2 on 2024-10-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0007_rename_call_to_action_text_content_cta_action_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
