# Generated by Django 5.1.2 on 2024-10-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0009_remove_content_enable_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='enable_gallery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='content',
            name='enable_uploads',
            field=models.BooleanField(default=True),
        ),
    ]
