# Generated by Django 5.1.2 on 2024-10-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0010_content_enable_gallery_content_enable_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='enable_gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='enable_uploads',
            field=models.BooleanField(default=False),
        ),
    ]
