# Generated by Django 5.1.2 on 2024-10-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('list', 'List')], default='text', max_length=100),
        ),
    ]
