# Generated by Django 5.1.2 on 2024-10-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_alter_settings_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('list', 'List')], default='list', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('parent_key', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'verbose_name': 'SelectList',
                'verbose_name_plural': 'SelectLists',
            },
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
