# Generated by Django 5.1.2 on 2024-10-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_alter_branch_code_alter_branch_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
