# Generated by Django 5.1.2 on 2024-10-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='page_layout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
