# Generated by Django 5.1.2 on 2024-10-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_alter_category_page_layout_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectlist',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
