# Generated by Django 5.1.2 on 2024-10-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_alter_selectlist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
